%% Constants
DIGITS = '0123456789+-=';
DIGITS_T = '0123456789pme';
N_DIGITS = length(DIGITS);

TRAINING_SAMPLES_PER_DIGIT = 7;
VALIDATION_SAMPLES_PER_DIGIT = 3;
SAMPLES_PER_DIGIT = TRAINING_SAMPLES_PER_DIGIT + VALIDATION_SAMPLES_PER_DIGIT;

N_RUNS = 30;

%% Structs
DIGIT_SIZE = struct();
DIGIT_SIZE.width = 5;
DIGIT_SIZE.height = 5;