%% Constants
%DIGITS = '0123456789+-=';
%DIGITS_T = '0123456789pme';
%N_DIGITS = length(DIGITS);

TRAINING_RATIO = 0.7;
VALIDATION_RATIO = 0.3;
%SAMPLES_PER_DIGIT = TRAINING_SAMPLES_PER_DIGIT + VALIDATION_SAMPLES_PER_DIGIT;

N_RUNS = 30;

%% Structs
DIGIT_SIZE = struct();
DIGIT_SIZE.width = 5;
DIGIT_SIZE.height = 5;